### ISSUE TITLE
Does this support as RF library?

### ISSUE THREAD

**Issue by KishoreNateshOfficial** [jezznar/JiphyLib#2]
Can we use it as keywords in RF by inputting Output.xml to the keywords? If so, is there a keyword doc?

**Comment by jezztify** [comment]
Hi @KishoreNatesh unfortunately, this does still does not have any documentations yet. I have added a new branch hotfix/issue-2. Please have a look at it. I'd appreciate it if you can give me a feedback. Thank you in advance

**Comment by jezztify** [comment]
closing issue. will open once feedback has been provided by the reporter.
